// District bounds updated 2× to match the expanded map scale
export const DISTRICTS = {
  ali_mendjeli: { id: 'ali_mendjeli', name: 'Ali Mendjeli', bounds: { x: [-400, -100], z: [-200, 200] }, color: '#ff8c00' },
  centre_ville: { id: 'centre_ville', name: 'Centre-Ville', bounds: { x: [-100, 200], z: [-200, 200] }, color: '#ffd700' },
  old_city:     { id: 'old_city',     name: 'Old City',     bounds: { x: [200,  500], z: [-100, 100] }, color: '#dc143c' },
  ain_mlila:    { id: 'ain_mlila',    name: "Ain M'lila",   bounds: { x: [-600, -400], z: [-200, 200] }, color: '#808080' },
  airport:      { id: 'airport',      name: 'Airport',      bounds: { x: [-400, -200], z: [200, 500] },  color: '#4169e1' },
} as const;

export const CAREER_PATHS = {
  street_thug: { level: 1, maxLevel: 4 },
  gangster: { level: 5, maxLevel: 9 },
  crime_boss: { level: 10, maxLevel: 14 },
  business_tycoon: { level: 15, maxLevel: 99 },
} as const;

export const I18N = {
  en: {
    start_game: "Start Game",
    new_game: "New Game",
    continue: "Continue",
    leaderboard: "Leaderboard",
    settings: "Settings",
    career_path: "Career Path",
    username: "Username",
    money: "DA",
    level: "Level",
    wanted: "Wanted",
    press_interact: "Press E to interact",
    press_attack: "Press F to attack",
    press_map: "Press M for map",
    resume: "Resume",
    save_game: "Save Game",
    exit_to_menu: "Exit to Main Menu",
    saved: "Saved!",
    map: "Map",
    missions: "Missions",
    shop: "Shop",
    vehicles: "Vehicles",
    properties: "Properties",
    weapons: "Weapons",
    buy: "Buy",
    owned: "OWNED",
    accept: "Accept",
    decline: "Decline",
    reward: "Reward",
    difficulty: "Difficulty",
    graphics: "Graphics Quality",
    audio: "Audio",
    controls: "Controls",
    language: "Language",
    low: "Low",
    medium: "Medium",
    high: "High",
    touch_controls: "Touch Controls",
    street_thug: "Street Thug",
    gangster: "Gangster",
    crime_boss: "Crime Boss",
    business_tycoon: "Business Tycoon",
    create_character: "Create Character",
    enter_vehicle: "Press E to enter vehicle",
    exit_vehicle: "Press F to exit vehicle",
    height: "Height (cm)",
    confirm: "Confirm",
    sign_in_google: "Sign in with Google",
    signed_in_as: "Signed in as",
    sign_out: "Sign out",
    cloud_save_hint: "Sign in to save your progress to the cloud",
  },
  ar: {
    start_game: "ابدأ اللعبة",
    new_game: "لعبة جديدة",
    continue: "متابعة",
    leaderboard: "لوحة المتصدرين",
    settings: "الإعدادات",
    career_path: "المسار المهني",
    username: "اسم المستخدم",
    money: "د.ج",
    level: "المستوى",
    wanted: "مطلوب",
    press_interact: "اضغط E للتفاعل",
    press_attack: "اضغط F للهجوم",
    press_map: "اضغط M للخريطة",
    resume: "متابعة",
    save_game: "حفظ اللعبة",
    exit_to_menu: "الخروج للقائمة الرئيسية",
    saved: "تم الحفظ!",
    map: "خريطة",
    missions: "مهمات",
    shop: "متجر",
    vehicles: "مركبات",
    properties: "عقارات",
    weapons: "أسلحة",
    buy: "شراء",
    owned: "مملوك",
    accept: "قبول",
    decline: "رفض",
    reward: "مكافأة",
    difficulty: "صعوبة",
    graphics: "جودة الرسومات",
    audio: "الصوت",
    controls: "التحكم",
    language: "اللغة",
    low: "منخفضة",
    medium: "متوسطة",
    high: "عالية",
    touch_controls: "أزرار اللمس",
    street_thug: "شاب من الشارع",
    gangster: "عضو عصابة",
    crime_boss: "رئيس عصابة",
    business_tycoon: "رجل أعمال",
    create_character: "إنشاء شخصية",
    enter_vehicle: "اضغط E لركوب السيارة",
    exit_vehicle: "اضغط F للنزول من السيارة",
    height: "الطول (سم)",
    confirm: "تأكيد",
    sign_in_google: "تسجيل الدخول عبر جوجل",
    signed_in_as: "تم تسجيل الدخول باسم",
    sign_out: "تسجيل الخروج",
    cloud_save_hint: "سجّل الدخول لحفظ تقدمك في السحابة",
  },
  fr: {
    start_game: "Démarrer",
    new_game: "Nouvelle Partie",
    continue: "Continuer",
    leaderboard: "Classement",
    settings: "Paramètres",
    career_path: "Parcours Professionnel",
    username: "Nom d'utilisateur",
    money: "DA",
    level: "Niveau",
    wanted: "Recherché",
    press_interact: "Appuyez sur E pour interagir",
    press_attack: "Appuyez sur F pour attaquer",
    press_map: "Appuyez sur M pour la carte",
    resume: "Reprendre",
    save_game: "Sauvegarder",
    exit_to_menu: "Quitter vers le Menu",
    saved: "Sauvegardé !",
    map: "Carte",
    missions: "Missions",
    shop: "Boutique",
    vehicles: "Véhicules",
    properties: "Propriétés",
    weapons: "Armes",
    buy: "Acheter",
    owned: "POSSÉDÉ",
    accept: "Accepter",
    decline: "Refuser",
    reward: "Récompense",
    difficulty: "Difficulté",
    graphics: "Qualité Graphique",
    audio: "Audio",
    controls: "Contrôles",
    language: "Langue",
    low: "Basse",
    medium: "Moyenne",
    high: "Haute",
    touch_controls: "Contrôles Tactiles",
    street_thug: "Gamin des rues",
    gangster: "Gangster",
    crime_boss: "Chef du crime",
    business_tycoon: "Homme d'affaires",
    create_character: "Créer un Personnage",
    enter_vehicle: "Appuyez sur E pour entrer dans le véhicule",
    exit_vehicle: "Appuyez sur F pour sortir du véhicule",
    height: "Taille (cm)",
    confirm: "Confirmer",
    sign_in_google: "Se connecter avec Google",
    signed_in_as: "Connecté en tant que",
    sign_out: "Se déconnecter",
    cloud_save_hint: "Connectez-vous pour sauvegarder votre progression dans le cloud",
  }
} as const;

export function t(key: keyof typeof I18N.en, lang: 'en' | 'ar' | 'fr' = 'en') {
  return I18N[lang][key] || I18N.en[key] || key;
}
